title: Adrien Mogenet
description: AI & Engineering leader | I help people and organisations make impactful decisions
google_analytics: UA-3648232-18
show_downloads: false
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
